# Lobot provides the default Capfile for you in case you want to use more cap later

# load 'deploy' if respond_to?(:namespace) # cap2 differentiator
# Dir['vendor/gems/*/recipes/*.rb','vendor/plugins/*/recipes/*.rb'].each { |plugin| load(plugin) }
# 
# load 'config/deploy' # remove this line to skip loading any of the default tasks